use crate::agent_kind::{HookEventSpec, HookStateEffect, PulseEffect, ReadEffect};

pub(crate) const CLAUDE_CODE: &[HookEventSpec] = &[
    HookEventSpec {
        native: "SessionStart",
        canonical: "session-start",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "UserPromptSubmit",
        canonical: "prompt",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::MarkRead,
        pulse: PulseEffect::Prompt,
    },
    HookEventSpec {
        native: "PreToolUse",
        canonical: "pre-tool",
        state: Some(HookStateEffect::ToolRunning),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "PostToolUse",
        canonical: "post-tool",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "Stop",
        canonical: "stop",
        state: Some(HookStateEffect::Idle),
        read: ReadEffect::MarkUnread,
        pulse: PulseEffect::Finished,
    },
    HookEventSpec {
        native: "Notification",
        canonical: "notification",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
    HookEventSpec {
        native: "SubagentStop",
        canonical: "subagent-stop",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Finished,
    },
    HookEventSpec {
        native: "PreCompact",
        canonical: "pre-compact",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Compact,
    },
    HookEventSpec {
        native: "SessionEnd",
        canonical: "session-end",
        state: Some(HookStateEffect::Idle),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Teardown,
    },
    HookEventSpec {
        native: "SubagentStart",
        canonical: "subagent-start",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "StopFailure",
        canonical: "stop-failure",
        state: Some(HookStateEffect::Idle),
        read: ReadEffect::MarkUnread,
        pulse: PulseEffect::Error,
    },
    HookEventSpec {
        native: "PostCompact",
        canonical: "post-compact",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Compact,
    },
    HookEventSpec {
        native: "PermissionRequest",
        canonical: "permission",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
    HookEventSpec {
        native: "Setup",
        canonical: "setup",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "UserPromptExpansion",
        canonical: "prompt-expand",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Prompt,
    },
    HookEventSpec {
        native: "PermissionDenied",
        canonical: "permission-denied",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
    HookEventSpec {
        native: "PostToolUseFailure",
        canonical: "post-tool-fail",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Error,
    },
    HookEventSpec {
        native: "PostToolBatch",
        canonical: "post-tool-batch",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "TaskCreated",
        canonical: "task-created",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "TaskCompleted",
        canonical: "task-completed",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Finished,
    },
    HookEventSpec {
        native: "TeammateIdle",
        canonical: "teammate-idle",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
    HookEventSpec {
        native: "InstructionsLoaded",
        canonical: "instructions-loaded",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::None,
    },
    HookEventSpec {
        native: "ConfigChange",
        canonical: "config-change",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
    HookEventSpec {
        native: "CwdChanged",
        canonical: "cwd-changed",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::None,
    },
    HookEventSpec {
        native: "FileChanged",
        canonical: "file-changed",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::None,
    },
    HookEventSpec {
        native: "WorktreeCreate",
        canonical: "worktree-create",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "WorktreeRemove",
        canonical: "worktree-remove",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Teardown,
    },
    HookEventSpec {
        native: "Elicitation",
        canonical: "elicitation",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
    HookEventSpec {
        native: "ElicitationResult",
        canonical: "elicitation-result",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::None,
    },
];

pub(crate) const CODEX: &[HookEventSpec] = &[
    HookEventSpec {
        native: "SessionStart",
        canonical: "session-start",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "UserPromptSubmit",
        canonical: "prompt",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::MarkRead,
        pulse: PulseEffect::Prompt,
    },
    HookEventSpec {
        native: "PreToolUse",
        canonical: "pre-tool",
        state: Some(HookStateEffect::ToolRunning),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "PostToolUse",
        canonical: "post-tool",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "Stop",
        canonical: "stop",
        state: Some(HookStateEffect::Idle),
        read: ReadEffect::MarkUnread,
        pulse: PulseEffect::Finished,
    },
    HookEventSpec {
        native: "PermissionRequest",
        canonical: "notification",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
];

pub(crate) const GEMINI: &[HookEventSpec] = &[
    HookEventSpec {
        native: "SessionStart",
        canonical: "session-start",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "BeforeTool",
        canonical: "pre-tool",
        state: Some(HookStateEffect::ToolRunning),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "AfterTool",
        canonical: "post-tool",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "BeforeAgent",
        canonical: "prompt",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::MarkRead,
        pulse: PulseEffect::Prompt,
    },
    HookEventSpec {
        native: "Stop",
        canonical: "stop",
        state: Some(HookStateEffect::Idle),
        read: ReadEffect::MarkUnread,
        pulse: PulseEffect::Finished,
    },
    HookEventSpec {
        native: "PreCompress",
        canonical: "pre-compact",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Compact,
    },
];

pub(crate) const CRUSH: &[HookEventSpec] = &[HookEventSpec {
    native: "PreToolUse",
    canonical: "pre-tool",
    state: Some(HookStateEffect::ToolRunning),
    read: ReadEffect::Preserve,
    pulse: PulseEffect::Tool,
}];

pub(crate) const CLINE: &[HookEventSpec] = &[
    HookEventSpec {
        native: "TaskStart",
        canonical: "session-start",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Session,
    },
    HookEventSpec {
        native: "UserPromptSubmit",
        canonical: "prompt",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::MarkRead,
        pulse: PulseEffect::Prompt,
    },
    HookEventSpec {
        native: "PreToolUse",
        canonical: "pre-tool",
        state: Some(HookStateEffect::ToolRunning),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "PostToolUse",
        canonical: "post-tool",
        state: Some(HookStateEffect::Working),
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Tool,
    },
    HookEventSpec {
        native: "TaskComplete",
        canonical: "stop",
        state: Some(HookStateEffect::Idle),
        read: ReadEffect::MarkUnread,
        pulse: PulseEffect::Finished,
    },
    HookEventSpec {
        native: "Notification",
        canonical: "notification",
        state: None,
        read: ReadEffect::Preserve,
        pulse: PulseEffect::Attention,
    },
];

pub(crate) const NONE: &[HookEventSpec] = &[];
